package lec13_exception01;

public class TryCatchFinally02 {
	public static void main(String[] args) {
		
		/*
		try {
			System.out.println("try-catch-finally 구문 실행");
			int allSum = 10/0; //exception 발생
		} catch (Exception e) {
			System.out.println("예외 발생");
		} finally {
			System.out.println("try-catch-finally 종료");
		}
		*/
		
		
	}
}
